tap "homebrew/bundle"
tap "homebrew/services"
brew "awscli"
brew "git"
brew "gnupg"
brew "go"
brew "grpcurl"
brew "jq"
brew "mas"
brew "nkf"
brew "ripgrep"
brew "tig"
brew "tmux"
brew "tree"
brew "vim"
brew "wget"
brew "z"
cask "1password"
cask "alfred"
cask "docker"
cask "figma"
cask "google-backup-and-sync"
cask "google-cloud-sdk"
cask "iterm2"
cask "jetbrains-toolbox"
cask "kindle"
cask "spotify"
mas "LINE", id: 539883307
mas "Magnet", id: 441258766
mas "OmniGraffle", id: 1142578753
mas "Todoist", id: 585829637
